### PR TITLE
Enable_all integration proposal #1

### PR DESCRIPTION
**Pull request by DaedalusBLN**
-wizard.py: after build extraction/install, check for a file called ".enableall" in userdata.
-startup.py: re-switch enable_addons setting to false after execution, to avoid further executions. If .enableall file is found, delete. Reload skin and profile at the end.

@drinfernoo 

Let me know what you think...

### CODE REVIEW

**Comment by DaedalusBLN** [comment]
@drinfernoo With the addition of [745364b](https://github.com/a4k-openproject/plugin.program.openwizard/pull/117/commits/745364b8e76d8d31a58d882b2c5f94ce6f7d762c), the feature is ready for review and modifications. There was an error in menu.py, which I hadn't modified. Also fixed a typo and moved the enable_all setting to the hidden section in settings.xml

**Comment by SerpentDrago** [comment]
Can you explain why you would need to enable all , addons are only disabled in kodi if installed improperly . Install addons properly before making your build and they will not be disabled once that build is restored as long as addons db file in intact . 

Either that or fix your addons.db file so the addon is shown as properly installed . This is not a wizard problem, its a build issue .

I have never had issues or need to force enable addons upon installing a build .

**Comment by DaedalusBLN** [comment]
@SerpentDrago Well, I know a handful of builders which made builds that did not overwrite the addons database for a variety of reasons, as there are often issues when 'importing' a database from another architecture/OS and system bit. Binary addons, pvr clients and Archive Support for example and some other dependencies fail to install. [An example case...](https://forum.kodi.tv/showthread.php?tid=340001)

A workaround for Leia was to not overwrite the addons database and utilize an autoexec.py to enable all addons and install these dependencies via the InstallAddon command or through mock dummy versions with 0.0.1 version number, with  \<platform>  set to **all**  in the addon.xml thus forcing an update, which also ensured that any binary/os-specific addons would install normally in the future as the addons database is the native one. And ship the rest of the addons normally in the zip and have the autoexec enable them on first start.

Two things changed with Matrix: the way the package manager works (not updating addons that are installed locally and not from a repo EXCEPT FOR repository add-ons and official repo add-ons). The second thing that changed is the AutoExec mechanism. Autoexecs are now regular add-ons called service.autoexec and need to be in the addons folder and they must be activated manually if they're not in the database, like normal addons.

Many builders (used to) use AutoExecs, so that functionality is pretty much lost in Matrix except if they include them in the database, thus necessarily activating them and obviously overwriting the target system's native addons database. Which people like arcsun advised me against....

I am currently using such a Python service script in builds, only including repository addons, addon_data and the "installation script" in them and I'm installing add-ons straight from their repositories, I'm actually going to open source my script and make it easy for non-experienced Kodi modders to utilize... The benefits of this method:

1. No hosting costs for builders since builds are essentially tiny.
2. Always up-to-date installations and 100% guaranteed updateable plugins in Matrix, as if the user installed them.
3. In complete respect to Kodi's package management system. :) Who knows how long we will be able to fool Kodi about the origin of addons by importing a foreign database.


This feature is completely optional the way I implemented it and only gets activated if a certain file is found within the extracted build's userdata folder (I called it .enableall). It only gets activated ONCE on first boot after a build install. The check for the file only happens during install (after extraction) and the wizard deletes the file afterwards.

This doesn't break or change any other function of the wizard, it essentially just restores an option to builders that was possible in Leia... 1. AutoExecs, 2. Not overwriting databases to avoid foreign platform errors or corruption.

I hope I was able to answer your question and I'm always happy to discuss it further or find other solutions/implementations.

Cheers!

**Comment by drinfernoo** [comment]
I think that I will merge this, even though I agree with @SerpentDrago that this feature isn't really needed by this wizard. AutoExec is not really a feature that is supported by Kodi anymore (obviously, as you're attempting to "work around" it's obsoletion), and backups made properly with this wizard handle any issues with the add-on database automatically.

It is actually *important* and *intended* that backups include the add-on database, so that situations like you're describing *don't* occur... and the wizard actually does properly handle the migration from one platform to another. For instance, in your example of binary add-ons like PVR clients and archive support, if a backup has been made **using the wizard**, then those add-ons are actually tracked during backup, and properly installed (the correct version for the platform being restored to) after restoring the backup.

The proper handling of the add-on database and binary add-ons is actually one of the **main** "selling points" of using the wizard to create and restore backups, rather than zipping them manually, as many "builders" have done in the past. It is also one of the key reasons that it is important for these users to keep in mind the difference between the various types of backups (builds, themes, etc...), as each type of backup contains different files, and are restored differently, in order to avoid the same issues that you are trying to prevent.

Regarding your "special" script-based approach, that is going to be left "on you", but if this PR helps you out, then I'm not opposed to it... since it isn't *required* in a build, and doesn't appear to break any other functionality.

I need to review a bit further, to ensure that none of the current fixed on the `matrix` branch are lost when this is merged, but it looks fine to me so far.

**Comment by SerpentDrago** [comment]
as Dr pointed out , one of the shining things this wizard does that wizards didnt' do before it is handle binary / platform specific addons . if you make the main build with the wizard it will handle that and the database for you when its installed on another platform . There was intensive work done and testing to make sure this is about as flawless as you can have . Its a shame people still think they need to fix binary's manually . 

Matrix Auto updates addons perfectly fine , from the repo they were installed from . I've tested this it works fine . You just need to be sure if its say a official addon , you enable the setting to Install from all repos . Then on top of that make sure that addon was installed though a repo in your case one you control . It will update perfectly fine . 

I'm still failing to see any of your issues that can not be handled a more official way then some crazy workaround , Sorry if i'm not understanding . Anything you pointed out is handled better in another way  . 

Either way its a non breaking change and i support dr's choice to just go ahead and merge this . Its not going to hurt anything . just wish more people were educated on the features and proper usage of the wizard . It avoids workarounds or needing to use autoexe scripts .

**Comment by DaedalusBLN** [comment]
closing this. Followup: #118

**Pull request closed without merging**
